[package]
name = "microunit"
version = "0.1.0"
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
clap = "3.0.0-beta.4"
tokio = "1.10"
tonic = "0.5"
prost = "0.8"

[build-dependencies]
tonic-build = "0.5"
